In [65]:
import numpy as np
from PIL import Image

In [66]:

# Open the image form working directory
image = Image.open('nj.jpg')
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)
# show the image


JPEG
(750, 750)
RGB


In [47]:
data = np.asarray(image)
# print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
# image2 = Image.fromarray(data)
# print(type(image2))

# print(image2.mode)
# print(image2.size)
# print(data)


(1440, 1440, 3)


In [67]:
# x1 ,  y1 = 1,1
# x2 , y2 = 2,2
cropped = data[0:500, 0:500]
print(cropped)
print(cropped.shape)


[[[248 244 241]
  [248 244 241]
  [248 244 241]
  ...
  [226 208 194]
  [226 208 194]
  [226 208 194]]

 [[248 244 241]
  [248 244 241]
  [248 244 241]
  ...
  [226 208 194]
  [226 208 194]
  [226 208 194]]

 [[248 244 241]
  [248 244 241]
  [248 244 241]
  ...
  [226 208 194]
  [226 208 194]
  [226 208 194]]

 ...

 [[185 170 167]
  [185 170 167]
  [185 170 167]
  ...
  [ 92  99 127]
  [ 93  98 127]
  [ 98 105 133]]

 [[184 169 166]
  [184 169 166]
  [184 169 166]
  ...
  [ 90  95 124]
  [ 91  96 125]
  [ 98 103 132]]

 [[184 169 166]
  [184 169 166]
  [184 169 166]
  ...
  [ 89  94 123]
  [ 91  96 125]
  [100 106 132]]]
(500, 500, 3)


In [76]:

cropped.save('ffff2.jpg')


AttributeError: 'numpy.ndarray' object has no attribute 'save'

In [73]:
im.show()

In [72]:
pwd


'C:\\Users\\R02-PC10\\Untitled Folder'